datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
jpa.default.properties.hibernate.hbm2ddl.auto: update
redis.uri: ${REDIS_URI:`redis://localhost`}
endpoints:
  prometheus:
    sensitive: false
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

